### ISSUE TITLE
Trouble running main Dialogue function 

### ISSUE THREAD

**Issue by amr15** [livnatje/DIALOGUE#1]
Hello, 
I'm able to get the test data set to run smoothly, but have been having trouble trying to get this to run with my own data.  
When moving to DIALOGUE.run(), I'm running into this error, and was wondering if you have any suggestions? I'm feeding it a list of cell type objects created using the make.cell.type function.  

"[1] "#************DIALOGUE Step I: PMD ************#"
Error in svd(xlist[[i]]) : a dimension is zero

Thanks!
Anu

**Comment by livnatje** [comment]
Hi Anu!

Could you print out a summary of the (cell.type) items in the list that you're providing as input? I think the problem might be there, particularly in the original feature space X.

Thanks,
Livnat

**Comment by livnatje** [comment]
I assume the issue was resolved, so closing this. Thanks!
