### ISSUE TITLE
10X scRNA-seq in DIALOGUE

### ISSUE THREAD

**Issue by zhangch365** [livnatje/DIALOGUE#15]
Hello,
     First of all, thanks for the great tool and thank you for your research!I’d like to apply it to my own 10X scRNA-seq data, and if it‘s possible for you to provide some tutorials or some advice for us. Thank you anyway for your research as well as for this fascinating tool！

**Comment by livnatje** [comment]
Thank you!

Did you see the [tutorial](https://github.com/livnatje/DIALOGUE/wiki/Tutorial)? The code is pretty straight forward to run, as all you need to provide is the gene expression matrix (e.g., TPM) and the matching Principle Components (or other initial embeddings) per cell type. I'm happy to answer any specific questions you might have.

**Comment by zhangch365** [comment]
Hi,
  thanks for your response and sorry to bother you again,i've successfully made rA list,but when i run the code  'R<-DIALOGUE.run(rA = rA,main = "test",k = 2,results.dir = "/dialogue/DIALOGUE.results/",plot.flag = T,conf = "cellQ",pheno = "pathology",n.genes = 100)',it got the error'Error: $ operator is invalid for atomic vectors'.I put my data in the link below，https://www.jianguoyun.com/p/DV2ClrAQvZvRChizwcMEIAA.Hope to hear from you and thanks a lot!

**Comment by zhangch365** [comment]
Hi,
  Thanks for your response and sorry to bother you again,I've successfully made my own rA list,but when i run the code  'R<-DIALOGUE.run(rA = rA,main = "test",k = 2,results.dir = "/dialogue/DIALOGUE.results/",plot.flag = T,conf = "cellQ",pheno = "pathology",n.genes = 100)',it got the error'Error: $ operator is invalid for atomic vectors'.I put my data in the link below，https://www.jianguoyun.com/p/DV2ClrAQvZvRChizwcMEIAA.Hope to hear from you and thanks a lot!

**Comment by livnatje** [comment]
Hi @zhangch365, thanks fro providing the data. We'll get back to you asap.

**Comment by Nusob888** [comment]
Hi, 
Thanks for a potentially great tool. I would second this issue post. As great as the tutorial is... I think it lacks some specific examples. 

I think the necessity for an example using 10X scRNAseq or any other platform is evidenced by the fact that multiple users in the issues have used different inputs for the function:

- I have seen some use raw counts, others normalised counts for the tpm input
- I have also seen different people set up cellQ in different formats. e.g. You have stated as the "scaled log-transformed number of reads and/or genes detected". Do you mean that Dialogue will calculate the scaled log number of reads/genes detected? or whether we need to input scaled log number of reads. (some users have used a ratio of UMI counts/gene counts. You can see how this might get irreproducible the more these confusions are left open. 

An example would be fantastic if you have time. I appreciate it is probably a simple problem, but I think there is a pressing need for some clarity so that people are not generating analysis and interpreting things incorrectly. 

Thanks in advance

**Comment by livnatje** [comment]
Hi @Nusob888,

Thanks for the feedback. We will provide additional information and more detailed step-by-step examples in the tutorial. 

As for your specific questions:
- It is recommended to use TPM (transcript per million), not counts. The TPMs are used in step 2 (HLM), where the model will use the total number of counts as a confounder, and therefore the results won't be very different with raw counts, but nonetheless, **the recommendation is to use TPM values**. 

- **Best to use "scaled log-transformed number of reads" as cellQ**. This should be provided as input to make.cell.type. It is also possible to use  "scaled log-transformed number of genes", but certainly NOT the ratio of UMI/gene counts. 

I hope this helps clarify these points.

**Comment by crazyhottommy** [comment]
> Hi, Thanks for a potentially great tool. I would second this issue post. As great as the tutorial is... I think it lacks some specific examples.
> 
> I think the necessity for an example using 10X scRNAseq or any other platform is evidenced by the fact that multiple users in the issues have used different inputs for the function:
> 
> * I have seen some use raw counts, others normalised counts for the tpm input
> * I have also seen different people set up cellQ in different formats. e.g. You have stated as the "scaled log-transformed number of reads and/or genes detected". Do you mean that Dialogue will calculate the scaled log number of reads/genes detected? or whether we need to input scaled log number of reads. (some users have used a ratio of UMI counts/gene counts. You can see how this might get irreproducible the more these confusions are left open.
> 
> An example would be fantastic if you have time. I appreciate it is probably a simple problem, but I think there is a pressing need for some clarity so that people are not generating analysis and interpreting things incorrectly.
> 
> Thanks in advance

+1 :)

**Comment by crazyhottommy** [comment]
> Hi, Thanks for a potentially great tool. I would second this issue post. As great as the tutorial is... I think it lacks some specific examples.
> 
> I think the necessity for an example using 10X scRNAseq or any other platform is evidenced by the fact that multiple users in the issues have used different inputs for the function:
> 
> * I have seen some use raw counts, others normalised counts for the tpm input
> * I have also seen different people set up cellQ in different formats. e.g. You have stated as the "scaled log-transformed number of reads and/or genes detected". Do you mean that Dialogue will calculate the scaled log number of reads/genes detected? or whether we need to input scaled log number of reads. (some users have used a ratio of UMI counts/gene counts. You can see how this might get irreproducible the more these confusions are left open.
> 
> An example would be fantastic if you have time. I appreciate it is probably a simple problem, but I think there is a pressing need for some clarity so that people are not generating analysis and interpreting things incorrectly.
> 
> Thanks in advance

see https://github.com/livnatje/DIALOGUE/issues/12#issuecomment-1204160256

**Comment by livnatje** [comment]
Hi @Nusob888 and @crazyhottommy, 

A [Seurat wrapper](https://github.com/livnatje/DIALOGUE/blob/master/R/DIALOGUE_SeuratExample.R) and a [toy example tutorial ](https://github.com/livnatje/DIALOGUE/wiki/Toy-example:-Running-DIALOGUE-with-Seurat-object
) showing how to un DIALOGUE with a Seurat object are now provided

I hope this helps.
