### ISSUE TITLE
MCP don't have gene

### ISSUE THREAD

**Issue by jisnoalia** [livnatje/DIALOGUE#19]
![img](https://raw.githubusercontent.com/jisnoalia/image/master/img/202206061020372.png)
as the picture show, mcp4 and mcp5 don't have the gene , what's the trouble with it?

**Comment by livnatje** [comment]
Did you use `k = 5`? I assume the 4th and 5th MCPs didn't pass statistical significance cutoffs. 

What do you see in `output$MCP.cell.types`?

Could you look at the empirical p-values (`output$emp.p`)? You may need to re-install and re-run to see the empirical p-value though.

**Comment by jisnoalia** [comment]
and I have another problem,how to choose the cellQ's  info?

**Comment by livnatje** [comment]
Hi @jisnoalia the cellQ should include the log-transformed number of reads per cell or log-transformed number of genes per cell.

If your data includes additional confounder that you would like to control for, you can use the `conf` input to `DIALOGUE.run` to control that. Just make sure to provide those cell features in the metadata input when you call `make.cell.type`.

Let me know if you still need my input on the other issue you had.

**Comment by livnatje** [comment]
I am closing this issue @jisnoalia. Let us know if you have any additional questions.

**Comment by jsim91** [comment]
@livnatje I have a similar issue/question. Are these (MCP1) results expected:

![image](https://github.com/user-attachments/assets/5bc4ed82-286c-4668-99fe-4afd3e602acc)
<img width="1014" alt="empty_mcp" src="https://github.com/user-attachments/assets/4ca0fa7f-da46-4b76-8588-5afa9a404a10">
