### ISSUE TITLE
allowed labels for `DIALOGUE.run(pheno=)`

### ISSUE THREAD

**Issue by yugeji** [livnatje/DIALOGUE#2]
Hello,

In the documentation for `DIALOGUE.run`, it specifies that the label passed into `pheno` should be binary. Is there a particular reason for this? Would it be possible to specify a continuous label/how might this affect `DIALOGUE`?

Thank you very much!

**Comment by livnatje** [comment]
Hi Yugeji,

You are right, the phenotype can also be multi-class or continuous. We will be releasing a new version of DIALOGUE soon, which will support these type of phenotypes as well.

Thanks,
Livnat

**Comment by livnatje** [comment]
@abs51295 and @yugeji a new set of functions was added to test the association of MCPs with multi-class/continuous features. Use `DIALOGUE.pheno.multiclass(R,pheno)` with the `pheno` input being a string denoting the name of the feature you'd like to test. This can now be multi-class or continuous. 

Let me know if you have any questions or encounter any issues. Thanks
