### ISSUE TITLE
I see `..` comparisons in the MCPs output

### ISSUE THREAD

**Issue by abs51295** [livnatje/DIALOGUE#20]
Hey @livnatje I see MCPs like this 
```("endothelial..up", "Tcell..up", "Tcell..up", "Bcell..up", "myeloid..up", "myeloid..up", "myeloid..up", "myeloid..up", "endothelial.down", "endothelial..down", "Tcell.down", "Tcell..down", "Tcell..down", "Bcell..down", "myeloid.down", "myeloid..down", "myeloid..down", "myeloid..down", "myeloid..down", "fibroblasts.down")```. I don't understand what are the `..` supposed to mean here?

Thanks.

**Comment by livnatje** [comment]
Hi @abs51295 , this might be some string conversion glitch. What were the original cell type names in the input?
