### ISSUE TITLE
No MCPs identified for these cell types

### ISSUE THREAD

**Issue by jfckkiu** [livnatje/DIALOGUE#21]
Hello, really impressive work and it’s really a useful tool to explore the global expression pattern under pathologic conditions. However, I encounter a problem almost torturing me a week. It will be grateful if you can reply to me.I have a 10X Seurat object consisted of 9 samples (3 WT and 6 Mutant, 30000+ cells), Two main celltypes were identified, including HSC lineage and MSC lineage. So I prepare the celltype input like this. 

######prepare the input######
rA <- vector('list')
for (i in 1:length(Seurat.list)){

   
   samples <- Seurat.list[[i]]@meta.data$sample %>% 
           data.frame() %>% 
           magrittr::set_rownames(rownames(Seurat.list[[i]]@meta.data)) %>%
           magrittr::set_colnames('samples') %>%
           pull(samples)
    X <- Seurat.list[[i]] %>%  FindVariableFeatures (selection.method = "vst", nfeatures = 2000) %>% 
          ScaleData(verbose = FALSE)  %>% 
         RunPCA(npcs = 50, do.print = FALSE, verbose = FALSE,set.seed=666) %>%
         Embeddings( reduction = "pca") %>%
         .[,1:30] %>% as.matrix()
    tpm <- Seurat.list[[i]] %>% NormalizeData() %>% GetAssayData(assay = "RNA", slot = "data") %>% as.matrix() %>% na.omit()  
    selected_genes <-colSums(t(tpm)) %>% .[.!=0] %>% names()
    tpm <- tpm[selected_genes,]
    metadata <- Seurat.list[[i]]@meta.data  %>% as.matrix()
    cellQ <- (Seurat.list[[i]]@meta.data$nFeature_RNA)/ (Seurat.list[[i]]@meta.data$nCount_RNA)  %>% 
           magrittr::set_names(rownames(Seurat.list[[i]]@meta.data)) 
    rA[[i]] <-  make.cell.type(name = names(Seurat.list)[i],tpm,samples,X,metadata,cellQ = cellQ)
}
names(rA) <- names(Seurat.list)
######the output######
[1] "Cell type name: HSC lineage"
[1] "Cell type name: MSC lineage"

However, when I try to run DIALOGUE.run uses the code below 

######DIALOGUE.run######
R<-DIALOGUE.run(rA = rA,main = "Mutant_vs_WT",k = 3,results.dir = "./output4/",center.flag = FALSE,
                plot.flag = T,pheno = "group",
                abn.c = 15,n.genes = 200,parallel.vs = T)
######the output######
[1] "#************DIALOGUE Step I: PMD ************#"
[1] "HSC lineage: Removing 1 of 30 features."
[1] "MSC lineage: Removing 2 of 30 features."

[1] "#************DIALOGUE Step II: HLM ************#"
[1] "#************DIALOGUE Step II (multilevel modeling): HSC lineage vs. MSC lineage ************#"
[1] "No MCPs identified for these cell types."
[1] "#************Finalizing the scores************#"
[1] "./output4//DIALOGUE2_Mutant_vs_WT.rds"

Error in `rownames<-`(`*tmp*`, value = paste0(x$program, ifelse(x$up, : attempt to set 'rownames' on an object with no dimensions
Traceback:

1. DIALOGUE.run(rA = rA, main = "Mutant_vs_WT", k = 3, results.dir = "./output4/", 
 .     center.flag = FALSE, plot.flag = T, pheno = "group", abn.c = 15, 
 .     n.genes = 200, parallel.vs = T)
2. DIALOGUE3(rA = rA, main = main, results.dir = results.dir, full.version = full.version, 
 .     pheno = pheno)
3. lapply(R$cell.types, function(x) {
 .     DLG.multi.get.gene.pval(x, R)
 . })
4. FUN(X[[i]], ...)
5. DLG.multi.get.gene.pval(x, R)
6. lapply(R[b1], f1)
7. FUN(X[[i]], ...)
8. `rownames<-`(`*tmp*`, value = paste0(x$program, ifelse(x$up, 
 .     ".up_", ".down_"), x$genes))
9. stop("attempt to set 'rownames' on an object with no dimensions")
###### the output######

It’s really stange no MCPs were found. I change the parameter n.genes from 10 to 1000, k from 3 to 10 and abn.c through 5 to 15. But I still got the similar error. I try to use the code from DIALOGUE.main.R, it also doesn’t work. So how can I solve this problem, hoping your response!

**Comment by livnatje** [comment]
Hi @jfckkiu, thanks for your interest in our method. Let's see what's happening with your data here.

Did you get any output file in your output directory? If so, could you check the correlations and empirical values you get from the first PMD step? You can see the code for that below

```
R<-readRDS(./output4//DIALOGUE2_Mutant_vs_WT.rds)
print("Initial MCP cross-cell-type correlations")
print(R$cca.cor)

print("Empirical p-values")
print(R$emp.p)
```

**Comment by jfckkiu** [comment]
Hi, @livnatje , sorry for the late response. These days  I am wondering whether this problem is related to the device. So I rerun the input on the server. But the error is similar. 
I actually get two output files, DIALOGUE1_Mutant_vs_WT.rds and DIALOGUE2_Mutant_vs_WT.rds 
So I  run the code below
> R<-readRDS(./output4//DIALOGUE2_Mutant_vs_WT.rds)
print("Initial MCP cross-cell-type correlations")
print(R$cca.cor)
print("Empirical p-values")
print(R$emp.p)

And I got the results like this
> [1] "Initial MCP cross-cell-type correlations"
$R
     HSC lineage_MSC lineage
MCP1               0.8120148
MCP2               0.7412446
 $P
     HSC lineage_MSC lineage
MCP1             0.007848912
MCP2             0.022285931
[1] "Empirical p-values"
          [,1]
MCP1 0.9271768
MCP2 0.9444941

So what's wrong with this output. Thanks for your help. I really hope to solve this problem because DIALOGUE will be an important tool for my following several projects.

**Comment by jfckkiu** [comment]
> 

Hi， @livnatje ，Thanks for your reply. I also consider the limited amount of samples might be a pivotal problem. Only 9 samples were included (3 control and 6 mutant). What's your suggestion if the included samples were limited, my following project will analyze 16 samples, I wonder whether it's enough for the analysis.

**Comment by livnatje** [comment]
Hi @jfckkiu, for the current dataset, you can try running DIALOGUE with `extra.sparse = T`, this will further regularize it and may allow you to identify MCPs with lower empirical p-values.

16 samples will be a better setting. Perhaps there is external data you can use for validation or in combination with yours?

**Comment by jfckkiu** [comment]
@livnatje , Hi, livnate, thanks for your kind response, I add the parameter ` extra.sparse = T`, but the results were sitll similar, maybe the limited sample count was a pivotal problem. Anyway, thanks you for your help. Hoping your other interesting publications soon.

> [1] "Initial MCP cross-cell-type correlations"
$R
     HSC lineage_MSC lineage
MCP1               0.8080908
MCP2               0.9439258
$P
     HSC lineage_MSC lineage
MCP1            0.0084030196
MCP2            0.0001301038
[1] "Empirical p-values"
          [,1]
MCP1 0.9518389
MCP2 0.1575207

**Comment by livnatje** [comment]
Thanks for the update @jfckkiu. I am closing this for now.
