### ISSUE TITLE
how to extract necessary parameters from seurat object into dialogue?

### ISSUE THREAD

**Issue by Wulin-Tan** [livnatje/DIALOGUE#22]
Hi, DIALOGUE is wonderful tool! when I tried the pbmc data from seurat, I came across problems as follows:

T_cell<-pbmc[,pbmc@meta.data$cell_type=="T"]
T_cell@meta.data<-subset(pbmc@meta.data,cell_type=="T")

tpm_T<-as.matrix(T_cell@assays$RNA@data)
samples_T<-as.vector(T_cell@meta.data$orig.ident)
X_T<-T_cell@reductions$pca@cell.embeddings
metadata_T<-T_cell@meta.data
cellQ_T<-as.vector(T_cell@meta.data$nFeature_RNA)
names(cellQ_T)<-row.names(T_cell@meta.data)
rA_T<-make.cell.type(name = "T",tpm=tpm_T,samples_T,X_T,metadata_T,cellQ = cellQ_T)

Error in `rownames<-`(`*tmp*`, value = ids.u) : 
  attempt to set 'rownames' on an object with no dimensions

and I think the problem is from the line
 "samples_T<-as.vector([T_cell@meta.data](mailto:T_cell@meta.data)$orig.ident)". It can not be of only the same elements. that means the it can not be from only one samples.
when I switched it with a vector of different elements, the make.cell.type worked. 
however, when I move on to run "DIALOGUE.run", it gave:
"Error: $ operator is invalid for atomic vectors"

any further suggestion? thanks a lot.

**Comment by wfma** [comment]
following this issue also!

**Comment by jasondanic** [comment]
Wondering about input of the "samples" parameter when analysing scRNA-seq data without spatial information too. 
Following this issue also.

**Comment by livnatje** [comment]
Hi @jasondanic, @wfma , and @Wulin-Tan! Sorry for the late response. Do you have data from multiple samples? If so, you will need to input the sample identity. If you are using spatial data then you need to define which "niche" each cell came from and that would be under "samples".

DIALOGUE needs either spatial data or scRNA data from multiple samples to be able to detect MCPs. 

Please let me know if you have additional questions or if this is still not clear.

Thanks!

**Comment by jasondanic** [comment]
Hi @livnatje, thanks for your reply! You have given me exactly what I want to know.
My understanding of this issue is that each cell must be grouped into "varied"(or multiple) samples or niches, otherwise it will not work for creating correct format of cell.type object and it surely will not work for "DIALOGUE.run" too.
