### ISSUE TITLE
Temp plotting error

### ISSUE THREAD

**Issue by majorkazer** [livnatje/DIALOGUE#24]
Hello,

I am trying to run DIALOGUE and keep running into the following error:

```{r}
[1] "#************Finalizing the scores************#"
[1] "~/analysis/Output_v3/CCC/v1/test/DIALOGUE2_DC + T.rds"
Error in plot.new() : 
  could not open file '/home/rstudio/.local/share/rstudio/notebooks/318B8359-cell_cell_communication_v1/1/DC1F473Cce853a3b/co8ym12tey575_t/_rs_chunk_plot_001.png'
```

My guess that there is something funky going on while trying to save an intermediate plot. I've run into similar issues with other packages saving temporary data when parallel processing wasn't appropriately set. Is DIALOGUE built for parallel processing, and if so, how do you set it up?

Thanks!

**Comment by majorkazer** [comment]
I just wiped my R session to try again without initializing any parallel processing and the error was resolved.

**Comment by livnatje** [comment]
Great! Thanks for the update @majorkazer!
