### ISSUE TITLE
Tutorial Example Issue: Error in beanplot : could not find function "beanplot"

### ISSUE THREAD

**Issue by 98xy** [livnatje/DIALOGUE#27]
Hi, I tried to test the example and am running into a few issues. When I run this code in the [example wiki](https://github.com/livnatje/DIALOGUE/wiki/Example):
`R<-DIALOGUE.run(rA = rA,main = "test",k = 2,results.dir = "test",
                plot.flag = T,conf = "cellQ",pheno = "pathology",n.genes = 100)`
it returned an error:
`Error in beanplot(scores ~ treatment * conditions, ll = 0, las = 2, main = main,  : 
  could not find function "beanplot"`
`In addition: Warning messages:`
`1: In file.remove(paste0(results.dir, "DIALOGUE1_", main, ".rds")) :
  cannot remove file 'testDIALOGUE1_test.rds', reason 'No such file or directory'`
`2: In file.remove(paste0(results.dir, "DIALOGUE2_", main, ".rds")) :
  cannot remove file 'testDIALOGUE2_test.rds', reason 'No such file or directory'`

Do you have any suggestions?
Thank you!

`platform       x86_64-w64-mingw32`
`system         x86_64, mingw32`
`version.string R version 4.2.1 (2022-06-23 ucrt)`

**Comment by sangwookbae** [comment]
For me, installing 'beanplot' package using CRAN or BiocManager solved the problem . 

>BiocManager::install('beanplot')

or

>install.packages('beanplot')

Hope it works.

**Comment by livnatje** [comment]
Thanks for letting us know. We added `beanplot` as a dependency.
