### ISSUE TITLE
Trouble finishing MCP analysis with Seurat input

### ISSUE THREAD

**Issue by VNurm** [livnatje/DIALOGUE#28]
The analysis runs fine, but when finilizing the analysis I run into trouble:

"#************Finalizing the scores************#"
[1] "Removing MCP2"
[1] "Removing MCP3"
[1] "Removing MCP4"
[1] "Removing MCP5"
[1] "Removing MCP1"
[1] "Removing MCP2"
[1] "Removing MCP3"
[1] "Removing MCP4"
[1] "Removing MCP5"
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

I've tried with several different parameters and cell.type inputs, and always get the same error.

Hopefully you can help!

Thanks!

**Comment by OnkarMulay** [comment]
Hi,
Were you able to solve the issue?

**Comment by livnatje** [comment]
@OnkarMulay and @VNurm, are you running DIALOGUE on a small dataset? This issue can be the result of not finding any statistically significant MCPs, which is often due to small samples size.

**Comment by VNurm** [comment]
Hi,

Yeah, it's a fairly small dataset, and I originally suspected that it could be the major cause here, but wasn't sure. 

I'll be sure to try it again with an expanded dataset using the new package!

Thank you very much!
