### ISSUE TITLE
NA reported for `phenoZ`

### ISSUE THREAD

**Issue by yugeji** [livnatje/DIALOGUE#3]
Hello!

I've been running `DIALOGUE` on my single-cell data, and when trying to check `results$phenoZ`, via `print(round(R$phenoZ,2))` as provided in the example, all I see are NA values. I've run the test example and this produces the values shown in the tutorial.

Would you happen to have a suggestion for what might be the issue with my dataset? Would it happen to have to do with the warnings `boundary (singular) fit: see ?isSingular` and `fixed-effect model matrix is rank deficient so dropping 1 column / coefficient` or is this normal? 

Thank you very much in advance!

**Comment by livnatje** [comment]
Hi Yugeji, 

Did you provide the phenotype information in `metadata` when preparing the input using `make.cell.type` function? Perhaps some of the information is missing? Also, please note that it is recommended to use only datasets with at least 15 samples and limit the number of covariates in the mixed-effects model only to those that are critical to control for. 

We will be releasing a new version of DIALOGUE soon, which will have additional functionalities and built-in guidelines for proper use when providing specific input. 

Best,
Livnat

**Comment by livnatje** [comment]
I assume the issue was resolved, so closing this. Thanks!

**Comment by livnatje** [comment]
I assume the issue was resolved, so closing this. Thanks!
