### ISSUE TITLE
Share the code for the figures published in the NBT

### ISSUE THREAD

**Issue by xiangrong7** [livnatje/DIALOGUE#38]
Thank you for developing such an interesting package. Would you be willing to share the code for the figures published in the NBT  so that we can reproduce the graphs and utilize them more effectively？

**Comment by livnatje** [comment]
Thank you @xiangrong7. Absolutely. We will provide this in the upcoming new release of DIALOGUE 2.0 along with additional features and examples.

**Comment by xiangrong7** [comment]
I am really looking forward to your updates. However, would you be willing to share them with me now? I am eager to give them a try, especially the content similar to Figure 2f, Figure 3a, 3b, and 3c. My email address is [907037571@qq.com](mailto:907037571@qq.com). Thank you once again.

**Comment by livnatje** [comment]
@xiangrong7, the code for reproducing the lung cancer spatial results is now provided here https://github.com/livnatje/DIALOGUE/wiki/Reproducing-the-lung-cancer-spatial-results-and-figures

Let us know if you have any additional questions.

Thanks,
Livnat
