### ISSUE TITLE
The link 'See the tutorial for more details' does not lead to tutorials

### ISSUE THREAD

**Issue by yao50985098** [livnatje/DIALOGUE#39]
Hi, I'm trying to start with DIALOGUE, but the 'Tutorial' link leads to the same page. Is there a Document for a quick start? 
Thank you!

**Comment by livnatje** [comment]
Hi @yao50985098

Yes, we are updating the tutorial and wiki. These will be available next week with new examples. 

Thanks

**Comment by livnatje** [comment]
@yao50985098 the tutorial is available. The only change from before is that there is now an additional function (DLG.get.param) to define input parameters.

**Comment by yao50985098** [comment]
Thank you for the quick response!
